=== PriyanshChaudhari/BWP-Lab/Lab-7/Q1/players.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="playersinfo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="player" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="player-name" />
                            <xs:element name="age" type="xs:int" />
                            <xs:element name="batting-average" type="xs:int" />
                            <xs:element name="highest-score" type="xs:int" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PriyanshChaudhari/BWP-Lab/Lab-7/Q1/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<playersinfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="players.xsd">
    <player>
        <player-name>Virat Kohli</player-name>
        <age>33</age>
        <batting-average>57</batting-average>
        <highest-score>183</highest-score>
    </player>
    <player>
        <player-name>Hardik Pandya</player-name>
        <age>28</age>
        <batting-average>33</batting-average>
        <highest-score>92</highest-score>
    </player>
    <player>
        <player-name>Jasprit Bumrah</player-name>
        <age>28</age>
        <batting-average>6</batting-average>
        <highest-score>34</highest-score>
    </player>
    <player>
        <player-name>Dinesh Karthik</player-name>
        <age>37</age>
        <batting-average>30</batting-average>
        <highest-score>79</highest-score>
    </player>
    <player>
        <player-name>Ravindra Jadeja</player-name>
        <age>33</age>
        <batting-average>32</batting-average>
        <highest-score>87</highest-score>
    </player>
</playersinfo>
