=== PriyanshChaudhari/BWP-Lab/Class Work/XML/marksheet.dtd
<!DOCTYPE marksheet
[
    <!ELEMENT marksheet (student*)>
    <!ELEMENT student (name, roll, branch, PRN, marks)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT roll (#PCDATA)>
    <!ELEMENT branch (#PCDATA)>
    <!ELEMENT PRN (#PCDATA)>
    <!ELEMENT marks (sub1, sub2, sub3)>
    <!ELEMENT sub1 (#PCDATA)>
    <!ELEMENT sub2 (#PCDATA)>
    <!ELEMENT sub3 (#PCDATA)>
]>

=== PriyanshChaudhari/BWP-Lab/Class Work/XML/marksheet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE marksheet SYSTEM "marksheet.dtd">
<marksheet>
    <student>
        <name> ABC </name>
        <roll> 1 </roll>
        <branch> CS </branch>
        <PRN> 9 </PRN>
        <marks>
            <sub1> 10 </sub1>
            <sub2> 20 </sub2>
            <sub3> 30 </sub3>
        </marks>
    </student>
</marksheet>
